import { followUser } from "./routes/users/follow_users";
import { getUserPosts } from "./routes/posts/get_posts";
import { createNewPost } from "./routes/posts/create_post";
import { removePost } from "./routes/posts/remove_post";
import { editPost } from "./routes/posts/edit_post";
import { registerUser } from "./routes/users/register_user";
import { getUserInfo } from "./routes/users/get_user_info";
import { changeProfilePicture } from "./routes/users/user_profile_picture";
import { changeCoverPicture } from "./routes/users/user_cover_photo";
import { userLogin } from "./routes/users/user_login";
import { getFollowingUsers } from "./routes/users/get_followings";
import { createNewComment } from "./routes/comments/create_comment";
import { getComments } from "./routes/comments/get_comments";
import { removeComment } from "./routes/comments/delete_comment";
import { editComment } from "./routes/comments/edit_comment";
import { checkUserComments } from "./routes/comments/check_user_comments";
import { getSuggestedUser } from "./routes/users/get_suggested_user";
import { getProfileUserInfo } from "./routes/users/get_profile_user";
import { postLike } from "./routes/posts/post_like";
import { getAllUsers } from "./routes/users/get_all_users";
import { Application } from "express";
import { unfollowUser } from "./routes/users/unfollow_users";
import { getOnlyUserPosts } from "./routes/posts/get_user_posts";

const requests = (app: Application) => {
  app.use(followUser);
  app.use(unfollowUser);
  app.use(editPost);
  app.use(getOnlyUserPosts);
  app.use(getUserPosts);
  app.use(createNewPost);
  app.use(removePost);
  app.use(registerUser);
  app.use(getUserInfo);
  app.use(changeProfilePicture);
  app.use(changeCoverPicture);
  app.use(userLogin);
  app.use(getFollowingUsers);
  app.use(createNewComment);
  app.use(getComments);
  app.use(removeComment);
  app.use(editComment);
  app.use(checkUserComments);
  app.use(getAllUsers);
  app.use(getSuggestedUser);
  app.use(getProfileUserInfo);
  app.use(postLike);
};

export default requests;
